### ISSUE TITLE
Fail to run import_trainingspeech.sh

### ISSUE THREAD

**Issue by GourmandGuedj** [Common-Voice/commonvoice-fr#86]
Hi, i'm running the Docker image but get stuck at the import_trainingspeech.sh step, where i get the following error: 

```
+ fr/import_trainingspeech.sh
+ pushd /home/trainer/ds/
~/ds ~
+ pip install Unidecode==1.0.23
Collecting Unidecode==1.0.23
  Downloading https://files.pythonhosted.org/packages/31/39/53096f9217b057cb049fe872b7fc7ce799a1a89b76cf917d9639e7a558b5/Unidecode-1.0.23-py2.py3-none-any.whl (237kB)
     |████████████████████████████████| 245kB 9.4MB/s 
Installing collected packages: Unidecode
Successfully installed Unidecode-1.0.23
+ '[' 0 = 1 ']'
+ '[' '!' -f /mnt/extracted/data/trainingspeech/ts_2019-04-11_fr_FR_train.csv ']'
+ python bin/import_ts.py /mnt/extracted/data/trainingspeech
No path "/mnt/extracted/data/trainingspeech" - creating ...
No archive "/mnt/extracted/data/trainingspeech/ts_2019-04-11_fr_FR.zip" - downloading...
Progress |#                                                                                       | 100% completedTraceback (most recent call last):
  File "bin/import_ts.py", line 197, in <module>
    _download_and_preprocess_data(cli_args.target_dir, cli_args.english_compatible)
  File "bin/import_ts.py", line 44, in _download_and_preprocess_data
    archive_path = maybe_download('ts_' + ARCHIVE_NAME + '.zip', target_dir, ARCHIVE_URL)
  File "/home/trainer/ds/bin/../util/downloader.py", line 26, in maybe_download
    bar.update(done)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/progressbar/bar.py", line 629, in update
    return self.update(value, force=force, **kwargs)
  File "/home/trainer/ds-train/lib/python3.6/site-packages/progressbar/bar.py", line 641, in update
    % (value, self.min_value, self.max_value))
ValueError: Value 278 is out of range, should be between 0 and 0
Progress |#    
``` 

I build & run the docker image on a GCP VM (Debian 9) but I do have the same error when tested in local. For now I commented `import_trainingspeech.sh` in ./fr/run.sh to skip this step

**Comment by lissyx** [comment]
Looks like TrainingSpeech archive has been unpublished. @nicolaspanel I understand you might be paying for that, but would it be possible we set up some other mirror ?

**Comment by lissyx** [comment]
> Looks like TrainingSpeech archive has been unpublished. @nicolaspanel I understand you might be paying for that, but would it be possible we set up some other mirror ?

@nicolaspanel Gentle ping?

**Comment by lissyx** [comment]
Will be dealt with upstream with proper mirroring of the dataset and updating the importer code : https://github.com/mozilla/DeepSpeech/issues/2715
